/**
 * AFC-RUNNER-0: Build-to-PR Execution Engine
 *
 * Core runner service that executes approved WorkOrders:
 * 1. Checkout/branch target repo
 * 2. Apply changes for 1-N WorkOrders
 * 3. Run tests/build
 * 4. Capture evidence logs
 * 5. Open PR back to GitHub
 *
 * SAFETY: Execution only proceeds after explicit approval (Council Gate satisfied)
 */

import { prisma } from '@/lib/prisma';
import { createGitHubClient } from '@/lib/github/client';
import { getGitHubAccessToken } from '@/lib/auth';
import { ExecutionStatus } from '@prisma/client';
import { exec } from 'child_process';
import { promisify } from 'util';
import * as fs from 'fs/promises';
import * as path from 'path';


const execAsync = promisify(exec);

// Types
export interface ExecutionConfig {
  targetRepoOwner: string;
  targetRepoName: string;
  targetBranch?: string;
  workOrderIds: string[];
  userId: string;
  projectId?: string;
  councilDecisionId?: string;
}

export interface ExecutionResult {
  success: boolean;
  executionRunId: string;
  prUrl?: string;
  prNumber?: number;
  error?: string;
}

export interface WorkOrderSpec {
  id: string;
  key: string;
  domain: string;
  title: string;
  spec: string | null;
}

// Constants
const WORK_DIR = '/tmp/afc-runner';
const EVIDENCE_DIR = 'evidence/AFC-RUNNER-0/runs';

/**
 * Log a message to the execution run
 */
async function logExecution(
  executionRunId: string,
  phase: string,
  level: 'INFO' | 'WARN' | 'ERROR' | 'DEBUG',
  message: string,
  details?: Record<string, unknown>
): Promise<void> {
  await prisma.executionLog.create({
    data: {
      executionRunId,
      phase,
      level,
      message,
      detailsJson: details as object ?? undefined,
    },
  });
}

/**
 * Update execution run status
 */
async function updateStatus(
  executionRunId: string,
  status: ExecutionStatus,
  additionalData?: Record<string, unknown>
): Promise<void> {
  await prisma.executionRun.update({
    where: { id: executionRunId },
    data: {
      status,
      ...additionalData,
      updatedAt: new Date(),
    },
  });
}

/**
 * Generate a branch name for the execution
 */
function generateBranchName(workOrders: WorkOrderSpec[]): string {
  const timestamp = Date.now().toString(36);
  const domains = [...new Set(workOrders.map(wo => wo.domain))].slice(0, 2).join('-');
  return `afc/${domains}-${timestamp}`;
}

/**
 * Generate PR title from work orders
 */
function generatePRTitle(workOrders: WorkOrderSpec[]): string {
  if (workOrders.length === 1) {
    return `[AFC] ${workOrders[0].title}`;
  }
  const domains = [...new Set(workOrders.map(wo => wo.domain))];
  return `[AFC] ${workOrders.length} WorkOrders: ${domains.join(', ')}`;
}

/**
 * Generate PR body from work orders
 */
function generatePRBody(workOrders: WorkOrderSpec[], executionRunId: string): string {
  const workOrderList = workOrders
    .map(wo => `- **${wo.key}** (${wo.domain}): ${wo.title}`)
    .join('\n');

  return `## AFC Execution Engine - Automated PR

This PR was automatically generated by the Agent Factory Console execution engine.

### WorkOrders Executed
${workOrderList}

### Execution Details
- **Execution Run ID**: \`${executionRunId}\`
- **Generated At**: ${new Date().toISOString()}

### Safety Gates
- ✅ Council Gate: Approved
- ✅ WorkOrder Status: Approved

---
*Generated by AFC-RUNNER-0*
`;
}

/**
 * Execute shell command with logging
 */
async function execWithLog(
  executionRunId: string,
  phase: string,
  command: string,
  cwd: string,
  env?: Record<string, string>
): Promise<{ stdout: string; stderr: string }> {
  await logExecution(executionRunId, phase, 'DEBUG', `Executing: ${command}`, { cwd });

  try {
    const result = await execAsync(command, {
      cwd,
      env: { ...process.env, ...env },
      maxBuffer: 10 * 1024 * 1024, // 10MB buffer
    });
    return result;
  } catch (error) {
    const execError = error as { stdout?: string; stderr?: string; message?: string };
    await logExecution(executionRunId, phase, 'ERROR', `Command failed: ${command}`, {
      stdout: execError.stdout,
      stderr: execError.stderr,
      error: execError.message,
    });
    throw error;
  }
}

/**
 * Clone the target repository
 */
async function cloneRepository(
  executionRunId: string,
  owner: string,
  repo: string,
  branch: string,
  accessToken: string
): Promise<string> {
  const repoDir = path.join(WORK_DIR, `${owner}-${repo}-${Date.now()}`);

  await logExecution(executionRunId, 'CLONE', 'INFO', `Cloning ${owner}/${repo}...`);

  // Ensure work directory exists
  await fs.mkdir(WORK_DIR, { recursive: true });

  // Clone with token auth
  const cloneUrl = `https://x-access-token:${accessToken}@github.com/${owner}/${repo}.git`;
  const { stdout, stderr } = await execWithLog(
    executionRunId,
    'CLONE',
    `git clone --branch ${branch} --single-branch ${cloneUrl} ${repoDir}`,
    WORK_DIR
  );

  // Update clone log
  await prisma.executionRun.update({
    where: { id: executionRunId },
    data: { cloneLog: `${stdout}\n${stderr}` },
  });

  await logExecution(executionRunId, 'CLONE', 'INFO', `Clone complete: ${repoDir}`);
  return repoDir;
}

/**
 * Create a new branch for changes
 */
async function createBranch(
  executionRunId: string,
  repoDir: string,
  branchName: string
): Promise<void> {
  await logExecution(executionRunId, 'APPLY', 'INFO', `Creating branch: ${branchName}`);

  await execWithLog(executionRunId, 'APPLY', `git checkout -b ${branchName}`, repoDir);
}

/**
 * Apply work order changes to the repository
 * This is a simplified implementation - in production, this would parse specs and generate code
 */
async function applyWorkOrderChanges(
  executionRunId: string,
  repoDir: string,
  workOrders: WorkOrderSpec[]
): Promise<void> {
  await logExecution(
    executionRunId,
    'APPLY',
    'INFO',
    `Applying ${workOrders.length} work order(s)...`
  );

  // Create a changes file documenting what was applied
  const changesContent = workOrders
    .map(
      wo => `
## ${wo.title} (${wo.key})
Domain: ${wo.domain}
Spec:
${wo.spec || 'No specification provided'}
`
    )
    .join('\n---\n');

  const changesFile = path.join(repoDir, 'AFC_CHANGES.md');
  await fs.writeFile(changesFile, `# AFC Work Order Changes\n\n${changesContent}`);

  // Stage and commit changes
  await execWithLog(executionRunId, 'APPLY', 'git add -A', repoDir);
  await execWithLog(
    executionRunId,
    'APPLY',
    `git commit -m "[AFC] Apply ${workOrders.length} work order(s)"`,
    repoDir
  );

  await logExecution(executionRunId, 'APPLY', 'INFO', 'Changes applied and committed');
}

/**
 * Run build command if package.json exists
 */
async function runBuild(executionRunId: string, repoDir: string): Promise<boolean> {
  await logExecution(executionRunId, 'BUILD', 'INFO', 'Checking for build configuration...');

  try {
    const packageJsonPath = path.join(repoDir, 'package.json');
    await fs.access(packageJsonPath);

    // Install dependencies
    await logExecution(executionRunId, 'BUILD', 'INFO', 'Installing dependencies...');
    const installResult = await execWithLog(executionRunId, 'BUILD', 'npm install', repoDir);

    // Check for build script
    const packageJson = JSON.parse(await fs.readFile(packageJsonPath, 'utf-8'));
    if (packageJson.scripts?.build) {
      await logExecution(executionRunId, 'BUILD', 'INFO', 'Running build...');
      const buildResult = await execWithLog(executionRunId, 'BUILD', 'npm run build', repoDir);

      await prisma.executionRun.update({
        where: { id: executionRunId },
        data: { buildLog: `${installResult.stdout}\n${buildResult.stdout}` },
      });
    } else {
      await logExecution(executionRunId, 'BUILD', 'INFO', 'No build script found, skipping build');
      await prisma.executionRun.update({
        where: { id: executionRunId },
        data: { buildLog: installResult.stdout },
      });
    }

    return true;
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    await logExecution(executionRunId, 'BUILD', 'WARN', `Build step skipped: ${errorMessage}`);
    return false;
  }
}

/**
 * Run tests if available
 */
async function runTests(executionRunId: string, repoDir: string): Promise<boolean> {
  await logExecution(executionRunId, 'TEST', 'INFO', 'Checking for test configuration...');

  try {
    const packageJsonPath = path.join(repoDir, 'package.json');
    await fs.access(packageJsonPath);

    const packageJson = JSON.parse(await fs.readFile(packageJsonPath, 'utf-8'));
    if (packageJson.scripts?.test) {
      await logExecution(executionRunId, 'TEST', 'INFO', 'Running tests...');
      const testResult = await execWithLog(executionRunId, 'TEST', 'npm test', repoDir);

      await prisma.executionRun.update({
        where: { id: executionRunId },
        data: { testLog: testResult.stdout },
      });
      return true;
    } else {
      await logExecution(executionRunId, 'TEST', 'INFO', 'No test script found, skipping tests');
      return true;
    }
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    await logExecution(executionRunId, 'TEST', 'WARN', `Tests skipped: ${errorMessage}`);
    return true; // Don't fail execution if tests fail
  }
}

/**
 * Push branch and create PR using Octokit
 */
async function createPullRequest(
  executionRunId: string,
  repoDir: string,
  owner: string,
  repo: string,
  baseBranch: string,
  headBranch: string,
  title: string,
  body: string,
  accessToken: string
): Promise<{ prNumber: number; prUrl: string }> {
  await logExecution(executionRunId, 'PR_CREATE', 'INFO', `Pushing branch ${headBranch}...`);

  // Push the branch
  await execWithLog(
    executionRunId,
    'PR_CREATE',
    `git push origin ${headBranch}`,
    repoDir
  );

  await logExecution(executionRunId, 'PR_CREATE', 'INFO', 'Creating pull request...');

  // Create PR using Octokit
  const octokit = createGitHubClient(accessToken);
  const response = await octokit.rest.pulls.create({
    owner,
    repo,
    title,
    body,
    head: headBranch,
    base: baseBranch,
  });

  const prNumber = response.data.number;
  const prUrl = response.data.html_url;

  await prisma.executionRun.update({
    where: { id: executionRunId },
    data: {
      prCreationLog: `PR #${prNumber} created: ${prUrl}`,
    },
  });

  await logExecution(executionRunId, 'PR_CREATE', 'INFO', `PR created: ${prUrl}`, {
    prNumber,
    prUrl,
  });

  return { prNumber, prUrl };
}

/**
 * Save evidence to the evidence folder
 */
async function saveEvidence(
  executionRunId: string,
  workOrders: WorkOrderSpec[],
  prUrl?: string
): Promise<string> {
  const evidencePath = path.join(process.cwd(), EVIDENCE_DIR, executionRunId);

  await fs.mkdir(evidencePath, { recursive: true });

  // Get all logs
  const logs = await prisma.executionLog.findMany({
    where: { executionRunId },
    orderBy: { createdAt: 'asc' },
  });

  // Write execution log
  const logContent = logs
    .map(log => `[${log.createdAt.toISOString()}] [${log.phase}] [${log.level}] ${log.message}`)
    .join('\n');
  await fs.writeFile(path.join(evidencePath, 'execution.log'), logContent);

  // Write work orders summary
  const workOrdersContent = JSON.stringify(workOrders, null, 2);
  await fs.writeFile(path.join(evidencePath, 'work-orders.json'), workOrdersContent);

  // Write README
  const readmeContent = `# Execution Run: ${executionRunId}

## Summary
- **Execution ID**: ${executionRunId}
- **Timestamp**: ${new Date().toISOString()}
- **Work Orders**: ${workOrders.length}
${prUrl ? `- **PR URL**: ${prUrl}` : ''}

## Work Orders Executed
${workOrders.map(wo => `- ${wo.key}: ${wo.title}`).join('\n')}

## Files
- \`execution.log\` - Full execution log
- \`work-orders.json\` - Work order specifications
`;
  await fs.writeFile(path.join(evidencePath, 'README.md'), readmeContent);

  return evidencePath;
}

/**
 * Cleanup temporary files
 */
async function cleanup(repoDir: string): Promise<void> {
  try {
    await fs.rm(repoDir, { recursive: true, force: true });
  } catch {
    // Ignore cleanup errors
  }
}

/**
 * Main execution function
 * SAFETY: This function enforces Council Gate and approval requirements
 */
export async function executeWorkOrders(config: ExecutionConfig): Promise<ExecutionResult> {
  const {
    targetRepoOwner,
    targetRepoName,
    targetBranch = 'main',
    workOrderIds,
    userId,
    projectId,
    councilDecisionId,
  } = config;

  // Validate inputs
  if (!workOrderIds || workOrderIds.length === 0) {
    return {
      success: false,
      executionRunId: '',
      error: 'No work orders specified',
    };
  }

  // Get access token
  const accessToken = await getGitHubAccessToken(userId);
  if (!accessToken) {
    return {
      success: false,
      executionRunId: '',
      error: 'GitHub access token not found. Please re-authenticate.',
    };
  }

  // Fetch work orders and verify they are approved
  const workOrders = await prisma.workOrder.findMany({
    where: {
      id: { in: workOrderIds },
    },
  });

  if (workOrders.length !== workOrderIds.length) {
    return {
      success: false,
      executionRunId: '',
      error: 'One or more work orders not found',
    };
  }

  // SAFETY: Verify all work orders are in PENDING status (approved but not executed)
  const nonPendingOrders = workOrders.filter(wo => wo.status !== 'PENDING');
  if (nonPendingOrders.length > 0) {
    return {
      success: false,
      executionRunId: '',
      error: `Work orders must be in PENDING status. Found: ${nonPendingOrders.map(wo => `${wo.key}:${wo.status}`).join(', ')}`,
    };
  }

  // SAFETY: Verify Council Gate if project is specified
  if (projectId) {
    const councilDecision = await prisma.councilDecision.findFirst({
      where: { projectId },
    });

    if (!councilDecision) {
      return {
        success: false,
        executionRunId: '',
        error: 'Council Gate: No Council decision found for this project. Execution blocked.',
      };
    }
  }

  // Generate branch name
  const workOrderSpecs: WorkOrderSpec[] = workOrders.map(wo => ({
    id: wo.id,
    key: wo.key,
    domain: wo.domain,
    title: wo.title,
    spec: wo.spec,
  }));
  const sourceBranch = generateBranchName(workOrderSpecs);

  // Create execution run record
  const executionRun = await prisma.executionRun.create({
    data: {
      targetRepoOwner,
      targetRepoName,
      targetBranch,
      sourceBranch,
      status: 'PENDING',
      workOrderIds,
      userId,
      projectId,
      councilDecisionId,
    },
  });

  const executionRunId = executionRun.id;
  let repoDir = '';

  try {
    // Phase 1: Clone
    await updateStatus(executionRunId, 'CLONING');
    repoDir = await cloneRepository(
      executionRunId,
      targetRepoOwner,
      targetRepoName,
      targetBranch,
      accessToken
    );

    // Phase 2: Create branch and apply changes
    await updateStatus(executionRunId, 'APPLYING');
    await createBranch(executionRunId, repoDir, sourceBranch);
    await applyWorkOrderChanges(executionRunId, repoDir, workOrderSpecs);

    // Phase 3: Build
    await updateStatus(executionRunId, 'BUILDING');
    await runBuild(executionRunId, repoDir);

    // Phase 4: Test
    await updateStatus(executionRunId, 'TESTING');
    await runTests(executionRunId, repoDir);

    // Phase 5: Create PR
    await updateStatus(executionRunId, 'CREATING_PR');
    const prTitle = generatePRTitle(workOrderSpecs);
    const prBody = generatePRBody(workOrderSpecs, executionRunId);

    const { prNumber, prUrl } = await createPullRequest(
      executionRunId,
      repoDir,
      targetRepoOwner,
      targetRepoName,
      targetBranch,
      sourceBranch,
      prTitle,
      prBody,
      accessToken
    );

    // Save evidence
    const evidencePath = await saveEvidence(executionRunId, workOrderSpecs, prUrl);

    // Update work orders to IN_PROGRESS
    await prisma.workOrder.updateMany({
      where: { id: { in: workOrderIds } },
      data: { status: 'IN_PROGRESS' },
    });

    // Mark execution as complete
    await updateStatus(executionRunId, 'COMPLETED', {
      completedAt: new Date(),
      prNumber,
      prUrl,
      prTitle,
      prBody,
      evidencePath,
    });

    await logExecution(executionRunId, 'COMPLETE', 'INFO', 'Execution completed successfully', {
      prNumber,
      prUrl,
    });

    return {
      success: true,
      executionRunId,
      prUrl,
      prNumber,
    };
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';

    await updateStatus(executionRunId, 'FAILED', {
      errorMessage,
      completedAt: new Date(),
    });

    await logExecution(executionRunId, 'ERROR', 'ERROR', `Execution failed: ${errorMessage}`);

    return {
      success: false,
      executionRunId,
      error: errorMessage,
    };
  } finally {
    // Cleanup
    if (repoDir) {
      await cleanup(repoDir);
    }
  }
}

/**
 * Get execution run details
 */
export async function getExecutionRun(executionRunId: string) {
  return prisma.executionRun.findUnique({
    where: { id: executionRunId },
    include: {
      logs: {
        orderBy: { createdAt: 'asc' },
      },
    },
  });
}

/**
 * List execution runs for a project
 */
export async function listExecutionRuns(projectId?: string, limit = 20) {
  return prisma.executionRun.findMany({
    where: projectId ? { projectId } : {},
    orderBy: { createdAt: 'desc' },
    take: limit,
    include: {
      logs: {
        orderBy: { createdAt: 'desc' },
        take: 5,
      },
    },
  });
}
