#!/bin/bash
# AFC-RUNNER-0: Proof-of-Life Demo Script (CLI version)
# Creates a real PR against orange-cab using gh CLI

set -e

TARGET_REPO="lemneya/orange-cab"
TARGET_BRANCH="main"
WORK_DIR="/tmp/afc-runner-demo-$$"
BRANCH_NAME="afc/runner-demo-$(date +%s)"

echo "=== AFC-RUNNER-0 Proof-of-Life Demo ==="
echo "Target: $TARGET_REPO"
echo "Branch: $BRANCH_NAME"
echo ""

# Clone
echo "Step 1: Cloning repository..."
gh repo clone "$TARGET_REPO" "$WORK_DIR" -- --branch "$TARGET_BRANCH" --single-branch
cd "$WORK_DIR"

# Create branch
echo "Step 2: Creating branch..."
git checkout -b "$BRANCH_NAME"

# Apply changes
echo "Step 3: Applying changes..."
cat > AFC_CHANGES.md << CHANGES
# AFC Work Order Changes

## AFC Runner Demo WorkOrder
- **Key**: afc-runner-demo
- **Domain**: demo
- **Title**: AFC-RUNNER-0 Proof-of-Life Demo

### Description
This file was created by the AFC Execution Engine to demonstrate the Build-to-PR flow.

### Execution Details
- **Generated At**: $(date -Iseconds)
- **Branch**: $BRANCH_NAME

---
*Generated by AFC-RUNNER-0*
CHANGES

# Commit
echo "Step 4: Committing changes..."
git add -A
git commit -m "[AFC-RUNNER-0] Proof-of-Life Demo"

# Push
echo "Step 5: Pushing branch..."
git push origin "$BRANCH_NAME"

# Create PR
echo "Step 6: Creating PR..."
PR_URL=$(gh pr create \
  --repo "$TARGET_REPO" \
  --title "[AFC-RUNNER-0] Proof-of-Life Demo PR" \
  --body "## AFC Execution Engine - Proof-of-Life Demo

This PR was automatically generated by the Agent Factory Console execution engine (AFC-RUNNER-0).

### Demo Details
- **Branch**: \`$BRANCH_NAME\`
- **Generated At**: $(date -Iseconds)

### Safety Gates
✅ Execution triggered via CLI demo script
✅ All actions logged to terminal

---
*Generated by AFC-RUNNER-0 Proof-of-Life Demo*" \
  --base "$TARGET_BRANCH" \
  --head "$BRANCH_NAME")

# Cleanup
echo "Step 7: Cleaning up..."
rm -rf "$WORK_DIR"

echo ""
echo "=== Demo Complete ==="
echo "PR URL: $PR_URL"
